steps:
  - name: 'gcr.io/cloud-builders/go'
    id: 'Compile application'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/qwiklabs-gcp-03-39acedf17a30/my-repository/hello-cloudbuild-dev:v2.0', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: ['push', 'us-east1-docker.pkg.dev/qwiklabs-gcp-03-39acedf17a30/my-repository/hello-cloudbuild-dev:v2.0']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['-n', 'dev', 'apply', '-f', 'dev/deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
options:
 logging: CLOUD_LOGGING_ONLY
