steps:
  - name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/qwiklabs-gcp-03-39acedf17a30/my-repository/hello-cloudbuild:v1.0', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/qwiklabs-gcp-03-39acedf17a30/my-repository/hello-cloudbuild:v1.0']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['-n', 'prod', 'apply', '-f', 'prod/deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
    - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
options:
  logging: CLOUD_LOGGING_ONLY
